In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/IMDB Dataset.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [3]:
df.shape

(50000, 2)

In [4]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.shape

(50000, 2)

In [8]:
df[df["sentiment"] == "positive"]["review"].iloc[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [9]:
df[df["sentiment"] == "negative"]["review"].iloc[0]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [10]:
df[df["review"].str.contains("<br", regex=False)].head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
df["review"].duplicated().sum()

np.int64(418)

In [12]:
df["review"].str.contains("<br", regex=False).sum()

np.int64(29200)

In [13]:
duplicates = df[df["review"].duplicated(keep=False)]

duplicates.sort_values("review").head(20)

                                                  review sentiment
34058  "Go Fish" garnered Rose Troche rightly or wron...  negative
47467  "Go Fish" garnered Rose Troche rightly or wron...  negative
29956  "Three" is a seriously dumb shipwreck movie. M...  negative
31488  "Three" is a seriously dumb shipwreck movie. M...  negative
47527  "Witchery" might just be the most incoherent a...  negative
2976   "Witchery" might just be the most incoherent a...  negative
7949   'Dead Letter Office' is a low-budget film abou...  negative
32260  'Dead Letter Office' is a low-budget film abou...  negative
18022  (Spoilers)<br /><br />Oh sure it's based on Mo...  negative
22449  (Spoilers)<br /><br />Oh sure it's based on Mo...  negative
30799  (This is a review of the later English release...  negative
25363  (This is a review of the later English release...  negative
39916  * Some spoilers *<br /><br />This movie is som...  negative
14353  * Some spoilers *<br /><br />This movie is som...  negative
30638  ***SPOILERS*** ***SPOILERS*** Well, seeing as ...  positive
23510  ***SPOILERS*** ***SPOILERS*** Well, seeing as ...  positive
12817  **SPOILERS** I rented "Tesis" (or "Thesis" in ...  negative
44097  **SPOILERS** I rented "Tesis" (or "Thesis" in ...  negative
15706  *SPOILERS*<br /><br />I don't care what anyone...  positive
41655  *SPOILERS*<br /><br />I don't care what anyone...  positive

In [14]:
duplicates["sentiment"].value_counts()

sentiment
negative    598
positive    226
Name: count, dtype: int64

In [15]:
conflicting = (
    df.groupby("review")["sentiment"]
      .nunique()
)

conflicting[conflicting > 1]

Series([], Name: sentiment, dtype: int64)

In [16]:
from src.data_preprocessing import clean_text

sample = "This movie was AMAZING!!!<br /><br />I loved it."

clean_text(sample)

'this movie was amazing!!! i loved it.'

In [17]:
df["clean_review"] = df["review"].apply(clean_text)

In [18]:
df[["review", "clean_review"]].head()

,review,clean_review
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,a wonderful little production. the filming tec...
2,I thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...","petter mattei's ""love in the time of money"" is..."

In [19]:
df["clean_review"].str.contains("<br", regex=False).sum()

np.int64(0)

In [20]:
df["clean_review"].str.contains(r"<[^>]+>", regex=True).sum()

np.int64(0)

In [21]:
df["clean_review"].duplicated().sum()

np.int64(422)

In [23]:
df = df.drop_duplicates(subset="clean_review").reset_index(drop=True)

In [24]:
df.shape

(49578, 3)

In [25]:
df["clean_review"] = df["review"].apply(clean_text)

In [26]:
df["clean_review"].str.contains(r"<[^>]+>", regex=True).sum()

np.int64(0)

In [27]:
df["clean_review"].duplicated().sum()

np.int64(0)

In [28]:
html_rows = df[df["clean_review"].str.contains(r"<[^>]+>", regex=True)]

html_rows[["review", "clean_review"]].to_string(index=False)

'Empty DataFrame\nColumns: [review, clean_review]\nIndex: []'

In [29]:
df["clean_review"] = df["review"].apply(clean_text)

In [30]:
df["clean_review"].str.contains(r"<[^>]+>", regex=True).sum()

np.int64(0)

In [31]:
df = df.drop_duplicates(subset="clean_review").reset_index(drop=True)

In [32]:
df.shape

(49578, 3)

In [33]:
df["clean_review"].duplicated().sum()

np.int64(0)

In [34]:
df["sentiment"].value_counts()

sentiment
positive    24882
negative    24696
Name: count, dtype: int64

In [35]:
df["label"] = df["sentiment"].map({
    "negative": 0,
    "positive": 1
})

In [36]:
df[["sentiment", "label"]].head()

  sentiment  label
0  positive      1
1  positive      1
2  positive      1
3  negative      0
4  positive      1

In [37]:
df["label"].isnull().sum()

np.int64(0)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X = df["clean_review"]
y = df["label"]

In [40]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [41]:
X_train.shape

(39662,)

In [42]:
X_test.shape

(9916,)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
vectorizer = TfidfVectorizer()

In [45]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [46]:
X_test_tfidf = vectorizer.transform(X_test)

In [47]:
print("Training:", X_train_tfidf.shape)
print("Testing:", X_test_tfidf.shape)

Training: (39662, 92735)
Testing: (9916, 92735)

In [48]:
print("Vocabulary size:", len(vectorizer.vocabulary_))

Vocabulary size: 92735

In [49]:
list(vectorizer.vocabulary_.items())[:20]

[('saw', 71473),
 ('this', 82411),
 ('film', 30189),
 ('on', 58320),
 ('tv', 85028),
 ('many', 50596),
 ('years', 91817),
 ('ago', 2768),
 ('and', 4082),
 ('when', 90048),
 ('got', 34821),
 ('tape', 81134),
 ('thought', 82476),
 ('that', 82133),
 ('was', 89340),
 ('reasonably', 66833),
 ('well', 89792),
 ('done', 24176),
 ('it', 42737),
 ('not', 57233)]

In [50]:
print("Training:", X_train_tfidf.shape)
print("Testing:", X_test_tfidf.shape)
print("Vocabulary size:", len(vectorizer.vocabulary_))

Training: (39662, 92735)
Testing: (9916, 92735)
Vocabulary size: 92735

In [51]:
print(X_train_tfidf[0])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 78 stored elements and shape (1, 92735)>
  Coords	Values
  (0, 71473)	0.1530147191292881
  (0, 82411)	0.18322391376954106
  (0, 30189)	0.1890649064112703
  (0, 58320)	0.06994559610696548
  (0, 85028)	0.08209501687956848
  (0, 50596)	0.12353254261761874
  (0, 91817)	0.07049101445179422
  (0, 2768)	0.1019222406541667
  (0, 4082)	0.04930662123744452
  (0, 90048)	0.04813652308175264
  (0, 34821)	0.07466278412664222
  (0, 81134)	0.13472081431591565
  (0, 82476)	0.07489209737224091
  (0, 82133)	0.08647869818473145
  (0, 89340)	0.23999938097843743
  (0, 66833)	0.1498907954799241
  (0, 89792)	0.1052601915481682
  (0, 24176)	0.07757190093157827
  (0, 42737)	0.10630115672753418
  (0, 57233)	0.14472608891414485
  (0, 82154)	0.192426405516242
  (0, 8763)	0.0630831111562081
  (0, 58001)	0.050168908887315296
  (0, 3335)	0.03943336386799178
  (0, 54808)	0.060431721256173715
  :	:
  (0, 6421)	0.16918594558532032
  (0, 7585)	0.15293713607759402
  (0, 29223)	0.09648076039657656
  (0, 23972)	0.06482683886542998
  (0, 23007)	0.2804566712588449
  (0, 4874)	0.17084921755114738
  (0, 2059)	0.08080729403762403
  (0, 59657)	0.14447802800172793
  (0, 77303)	0.1446686734839831
  (0, 4872)	0.17741944259974252
  (0, 56557)	0.0887025475953143
  (0, 92030)	0.03812070111320578
  (0, 89400)	0.06012390386665304
  (0, 92052)	0.06588019991112086
  (0, 29156)	0.08381101272720007
  (0, 47186)	0.11108845875397748
  (0, 76305)	0.04659155822943577
  (0, 52526)	0.15226956978784967
  (0, 5133)	0.037970150482954684
  (0, 38136)	0.13142861463655875
  (0, 40761)	0.026889492142859756
  (0, 59216)	0.09384486541698282
  (0, 35231)	0.05664128497964968
  (0, 34060)	0.07446581537380595
  (0, 47)	0.07141987715282447

In [52]:
from sklearn.linear_model import LogisticRegression

In [53]:
model = LogisticRegression(max_iter=1000)

In [54]:
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [55]:
y_pred = model.predict(X_test_tfidf)

In [56]:
print(y_pred[:20])

[1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1]

In [57]:
print(y_test.values[:20])

[1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1]

In [58]:
from sklearn.metrics import accuracy_score

In [59]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8970350947962888

In [60]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.90      4939
           1       0.89      0.91      0.90      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [61]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[4365  574]
 [ 447 4530]]

In [62]:
y_pred = model.predict(X_test_tfidf)

In [63]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8970350947962888

In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.90      4939
           1       0.89      0.91      0.90      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [65]:
print(confusion_matrix(y_test, y_pred))

[[4365  574]
 [ 447 4530]]

In [66]:
examples = [
    "I absolutely loved this movie!",
    "This was one of the worst movies I have ever watched.",
    "The movie was okay, nothing special.",
    "The acting was brilliant and the story was fantastic.",
    "I expected much more from this film."
]

In [67]:
example_tfidf = vectorizer.transform(examples)

In [68]:
predictions = model.predict(example_tfidf)

In [69]:
for text, prediction in zip(examples, predictions):
    sentiment = "Positive" if prediction == 1 else "Negative"
    print(f"{sentiment}: {text}")

Positive: I absolutely loved this movie!
Negative: This was one of the worst movies I have ever watched.
Negative: The movie was okay, nothing special.
Positive: The acting was brilliant and the story was fantastic.
Positive: I expected much more from this film.

In [70]:
test_examples = [
    "I loved the acting but the story was terrible.",
    "The movie started slowly but became absolutely fantastic.",
    "Not bad, but definitely not great.",
    "I thought this movie would be amazing, but I was disappointed.",
    "This is not a good movie."
]

test_tfidf = vectorizer.transform(test_examples)
test_predictions = model.predict(test_tfidf)

for text, prediction in zip(test_examples, test_predictions):
    sentiment = "Positive" if prediction == 1 else "Negative"
    print(f"{sentiment}: {text}")

Negative: I loved the acting but the story was terrible.
Positive: The movie started slowly but became absolutely fantastic.
Positive: Not bad, but definitely not great.
Negative: I thought this movie would be amazing, but I was disappointed.
Positive: This is not a good movie.

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer

bigram_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2)
)

In [72]:
X_train_bigram = bigram_vectorizer.fit_transform(X_train)

In [73]:
X_test_bigram = bigram_vectorizer.transform(X_test)

In [74]:
print("Training:", X_train_bigram.shape)
print("Testing:", X_test_bigram.shape)
print("Vocabulary size:", len(bigram_vectorizer.vocabulary_))

Training: (39662, 2115846)
Testing: (9916, 2115846)
Vocabulary size: 2115846

In [75]:
bigram_model = LogisticRegression(max_iter=1000)

In [76]:
bigram_model.fit(X_train_bigram, y_train)

LogisticRegression(max_iter=1000)

In [77]:
y_pred_bigram = bigram_model.predict(X_test_bigram)

In [78]:
from sklearn.metrics import accuracy_score, classification_report

bigram_accuracy = accuracy_score(y_test, y_pred_bigram)

print("Bigram Accuracy:", bigram_accuracy)

Bigram Accuracy: 0.9004638967325534

In [79]:
print(classification_report(y_test, y_pred_bigram))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      4939
           1       0.89      0.92      0.90      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [80]:
test_tfidf_bigram = bigram_vectorizer.transform(test_examples)

test_predictions_bigram = bigram_model.predict(test_tfidf_bigram)

for text, prediction in zip(test_examples, test_predictions_bigram):
    sentiment = "Positive" if prediction == 1 else "Negative"
    print(f"{sentiment}: {text}")

Negative: I loved the acting but the story was terrible.
Positive: The movie started slowly but became absolutely fantastic.
Negative: Not bad, but definitely not great.
Negative: I thought this movie would be amazing, but I was disappointed.
Negative: This is not a good movie.

In [84]:
limited_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=100000
)

In [85]:
X_train_limited = limited_vectorizer.fit_transform(X_train)
X_test_limited = limited_vectorizer.transform(X_test)

In [86]:
print("Training:", X_train_limited.shape)
print("Testing:", X_test_limited.shape)
print("Vocabulary size:", len(limited_vectorizer.vocabulary_))

Training: (39662, 100000)
Testing: (9916, 100000)
Vocabulary size: 100000

In [87]:
limited_model = LogisticRegression(max_iter=1000)

limited_model.fit(X_train_limited, y_train)

LogisticRegression(max_iter=1000)

In [88]:
y_pred_limited = limited_model.predict(X_test_limited)

In [89]:
limited_accuracy = accuracy_score(y_test, y_pred_limited)

print("Limited Bigram Accuracy:", limited_accuracy)
print(classification_report(y_test, y_pred_limited))

Limited Bigram Accuracy: 0.9043969342476805
              precision    recall  f1-score   support

           0       0.92      0.89      0.90      4939
           1       0.89      0.92      0.91      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [90]:
results = {
    "TF-IDF Unigram": 0.8969342476805163,
    "TF-IDF Unigram + Bigram": 0.9004638967325534,
    "TF-IDF Bigram + 100k Features": 0.9043969342476805
}

results

{'TF-IDF Unigram': 0.8969342476805163,
 'TF-IDF Unigram + Bigram': 0.9004638967325534,
 'TF-IDF Bigram + 100k Features': 0.9043969342476805}

In [91]:
stopword_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=100000,
    stop_words="english"
)

In [92]:
X_train_stop = stopword_vectorizer.fit_transform(X_train)

In [93]:
X_test_stop = stopword_vectorizer.transform(X_test)

In [94]:
print("Training:", X_train_stop.shape)
print("Testing:", X_test_stop.shape)
print("Vocabulary size:", len(stopword_vectorizer.vocabulary_))

Training: (39662, 100000)
Testing: (9916, 100000)
Vocabulary size: 100000

In [95]:
stopword_model = LogisticRegression(max_iter=1000)

stopword_model.fit(X_train_stop, y_train)

LogisticRegression(max_iter=1000)

In [96]:
y_pred_stop = stopword_model.predict(X_test_stop)

In [97]:
stopword_accuracy = accuracy_score(y_test, y_pred_stop)

print("Stopword Accuracy:", stopword_accuracy)
print(classification_report(y_test, y_pred_stop))

Stopword Accuracy: 0.8970350947962888
              precision    recall  f1-score   support

           0       0.91      0.88      0.89      4939
           1       0.88      0.91      0.90      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [98]:
results["TF-IDF Bigram + 100k + Stopwords"] = stopword_accuracy

results

{'TF-IDF Unigram': 0.8969342476805163,
 'TF-IDF Unigram + Bigram': 0.9004638967325534,
 'TF-IDF Bigram + 100k Features': 0.9043969342476805,
 'TF-IDF Bigram + 100k + Stopwords': 0.8970350947962888}

In [99]:
test_tfidf_stop = stopword_vectorizer.transform(test_examples)

test_predictions_stop = stopword_model.predict(test_tfidf_stop)

for text, prediction in zip(test_examples, test_predictions_stop):
    sentiment = "Positive" if prediction == 1 else "Negative"
    print(f"{sentiment}: {text}")

Negative: I loved the acting but the story was terrible.
Positive: The movie started slowly but became absolutely fantastic.
Positive: Not bad, but definitely not great.
Positive: I thought this movie would be amazing, but I was disappointed.
Positive: This is not a good movie.

In [100]:
from sklearn.feature_extraction.text import CountVectorizer

In [101]:
bow_vectorizer = CountVectorizer(
    ngram_range=(1, 2),
    max_features=100000
)

In [102]:
X_train_bow = bow_vectorizer.fit_transform(X_train)

In [103]:
X_test_bow = bow_vectorizer.transform(X_test)

In [104]:
print("Training:", X_train_bow.shape)
print("Testing:", X_test_bow.shape)
print("Vocabulary size:", len(bow_vectorizer.vocabulary_))

Training: (39662, 100000)
Testing: (9916, 100000)
Vocabulary size: 100000

In [105]:
bow_model = LogisticRegression(max_iter=1000)

bow_model.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [106]:
y_pred_bow = bow_model.predict(X_test_bow)

In [107]:
bow_accuracy = accuracy_score(y_test, y_pred_bow)

print("BoW Accuracy:", bow_accuracy)
print(classification_report(y_test, y_pred_bow))

BoW Accuracy: 0.904497781363453
              precision    recall  f1-score   support

           0       0.91      0.90      0.90      4939
           1       0.90      0.91      0.91      4977

    accuracy                           0.90      9916
   macro avg       0.90      0.90      0.90      9916
weighted avg       0.90      0.90      0.90      9916

In [108]:
sample = ["This movie is absolutely amazing!"]

In [109]:
demo_vectorizer = TfidfVectorizer()

demo_vectorizer.fit(sample)

print(demo_vectorizer.get_feature_names_out())

['absolutely' 'amazing' 'is' 'movie' 'this']

In [110]:
from src.feature_extraction import create_tfidf_vectorizer

final_vectorizer = create_tfidf_vectorizer()

In [111]:
X_train_final = final_vectorizer.fit_transform(X_train)
X_test_final = final_vectorizer.transform(X_test)

In [112]:
print(X_train_final.shape)
print(X_test_final.shape)

(39662, 100000)
(9916, 100000)